//Post Actions
const SAVE_POST = 'SAVE_POST';

export{
    SAVE_POST
}

//Notification Actions
const NEW_NOTIFICATION = 'NEW_NOTIFICATION'
const READ_NOTIFICATION = 'READ_NOTIFICATION'

export{
    NEW_NOTIFICATION,
    READ_NOTIFICATION
}